### ISSUE TITLE
gateway codes on successful_payment_notification

### ISSUE THREAD

**Issue by jaykwonpark** [recurly/recurly-client-python#201]
Hi, I'm developing webhook server in python.

In test mode I'm receiving below on successful_payment_notification.

```
    ....
    <gateway>test</gateway>
    <payment_method>credit_card</payment_method>
    ....
```
Could I ask the contents of the gateway element for paypal payflowpro and authorize.net on production mode?

Thanks.

**Comment by bhelx** [comment]
@jaykwonpark Here is alist of all the gateway types in yaml form. You'll get the key as the `payment_method`. So in your case you'll see the strings `payflowpro` and `authorize`.

```yaml
gateway_type:
  test: Test Gateway
  authorize: Authorize.Net
  beanstream: Beanstream
  braintree_blue: Braintree
  braintree_orange: Braintree (Orange - v1)
  cybersource: CyberSource
  qbms: Intuit Merchant Services for QuickBooks
  linkpoint: LinkPoint / First Data
  litle_online: Vantiv (Litle Online)
  mes: Merchant e-Solutions
  ogone: Ogone
  orbital: Chase Paymentech Orbital
  payflowpro: PayPal Payflow Pro
  payflowpro_uk: PayPal Payflow Pro (UK)
  paypal_business: PayPal Business Account
  paypal: PayPal Payments Pro (US)
  paypal_ca: PayPal Payments Pro (CA)
  paypal_uk: PayPal Payments Pro (UK)
  sagepay_uk: SagePay (UK)
  tsys: Recurly Gateway
  wirecard: Wirecard
```
